theme: jekyll-theme-cayman
title: Call4Buddies
description:
    en: Do you know someone who could participate in our event?
    es: ¿Conoces a alguien que podría participar en nuestro evento?
plugins:
  - jekyll-redirect-from
